### ISSUE TITLE
readme out of date

### ISSUE THREAD

**Issue by bengreenier** [bengreenier/overlayed#43]
Oops! Our main readme is missing some important updates! 🙈 

We should document that [built-in plugins](https://github.com/bengreenier/overlayed#built-in-overlays) are, in fact, configurable! All plugins are now configurable by adding an object to the configuration file containing the plugin config, indexed by the plugin name.

For instance:

```
{
    "clock": {
       "locale": "en-US"
    }
}
```

We should also clarify that these plugins can be hidden if they have a key `hidden` set to `true`. For instance:

```
{
    "clock": {
       "hidden": true
    }
}
```

That addresses the issue for built-in plugins, but this approach also works for [custom plugins](https://github.com/bengreenier/overlayed#custom-overlays) too. We should clarify that as well. 🚀 🎸

**Comment by CadenG150** [comment]
I made a pull request for this.
